### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/mediadrop_ynh#1]
Unable to install on my yunohost test server:
!!

mediadrop install's script has encountered an error. Installation was cancelled.

!!

sudo: paster: command not found

+ sudo paster make-config MediaDrop /opt/mediadrop/deployment.ini

Finished processing dependencies for MediaDrop==0.11dev

Note: Bypassing https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2 (disallowed host; see http://bit.ly/1dg9ijs for details).

Note: Bypassing https://pypi.python.org/packages/source/c/certifi/certifi-1.0.1.tar.gz#md5=45f5cb94b8af9e1df0f9450a8f61b790 (disallowed host; see http://bit.ly/1dg9ijs for details).

Using /opt/mediadrop/venv/lib/python2.7/site-packages

Installing easy_install script to /opt/mediadrop/venv/bin

Installing easy_install-3.4 script to /opt/mediadrop/venv/bin

**Comment by magikcypress** [comment]
Thanks again for this report!
I have fixe some bugs, but i can't connect to admin :-1:. I try to know why.
