### ISSUE TITLE
Avoid removing YunoHost on application remove !

### ISSUE THREAD

**Issue by opi** [YunoHost-Apps/mediadrop_ynh#4]
https://github.com/YunoHost-Apps/mediadrop_ynh/blob/master/scripts/remove#L52-L55

See this log https://paste.yunohost.org/ilimitufos.xml , some user on support@ channel report that his installation failed (it happens), then the remove script was lanched, and every yunohost-* package was removed from his machine :/

**Comment by magikcypress** [comment]
bad new ! :( 
i comment remove package. I'll try to find a solution for that!

**Comment by isAAAc** [comment]
i just tried to install this app, it fails, and yunohost package gone away

**Comment by yalh76** [comment]
Repaired now after full upgarde

**Comment by yalh76** [comment]
Can be closed

**Comment by frju365** [comment]
@yalh76 : do you want to be the maintainer of the package mediadrop (this repo) ?

**Comment by yalh76** [comment]
@frju365 No ^^, not interested by this app.
I was just bored to test it with other Yunohost packages and it brokes my yunohost test VM. 

And guys didn't want to remove it from the community.json (https://github.com/YunoHost/apps/pull/660), I decide to fix it in case I try to test it having forgotten it will break my Yunohost VM
